### ISSUE TITLE
 AttributeError while requesting services with "wmsOnly: true" 

### ISSUE THREAD

**Issue by danceb** [qwc-services/qwc-ogc-service#16]
This issue occurs with the current ogc service v2023.12.22, it works with v2023.12.19.

I am not sure, but I think this only occurs with wms services, which are configured as "wmsOnly". While requesting such a service via GetMap for instance I am getting this error:
```
AttributeError: 'OGCService' object has no attribute 'expand_group_layers_and_opacities'. Did you mean: 'expand_group_layers_opacities_styles'?
```

**Comment by manisandro** [comment]
Thanks, should be fixed in v2024.01.05.
